### GET Movies
GET http://localhost:5000/movies

//Pamiętaj że id masz na /movies
### GET Movie by ID
GET http://localhost:5000/movies/683c3d6485afcf9d217f2dcd

### PUT Movie
PUT http://localhost:5000/movies/683c3d6485afcf9d217f2dcd
Content-Type: application/json

{
  "genre": "Comedy Drama"
}

### DELETE Movie
DELETE http://localhost:5000/movies/683c3e9885afcf9d217f2dd4

### POST Movie
POST http://localhost:5000/movies
Content-Type: application/json

{
  "title": "How to sell drugs online(fast)",
  "releaseYear": 2019,
  "genre": "Comedy",
  "director": "Lars Montag",
  "cast": [
    "Maximilian Mundt",
    "Danilo Kamber",
    "Damian Hardung",
    "Luna Baptiste Schaller",
    "Bjarne Mädel",
    "Leonie Wesselow"
  ],
  "rating": 10,
  "description": "To impress his former girlfriend, a nerdy teen starts selling drugs online out of his bedroom, and soon becomes one of Europe's biggest dealers."
}

### POST Review
POST http://localhost:5000/reviews
Content-Type: application/json

{
  "author": "Franek Czarnech",
  "content": "Moją pasją są konie i narkotyki więc idealny film dla mnie",
  "movieId": "683c3c8185afcf9d217f2dc7"
}

### Get Review
GET http://localhost:5000/reviews


### PUT Review
PUT http://localhost:5000/reviews/683c3d6485afcf9d217f2dcd
Content-Type: application/json

{
  "content": "Ludzie mówili że słaby, ale mnie się podobało"
}


### DELETE Review
DELETE http://localhost:5000/reviews/683c3c8185afcf9d217f2dc7
